### ISSUE TITLE
Relaxing Limit init

### ISSUE THREAD

**Issue by jlipford** [draekien/Draekien.FluentUtils#17]
Would you be open to relaxing the Limit init set config?  Will make it easier to use extension methods to auto set the limit, offset params from 3rd party component libs.

Right now the init restricts its setting only through constructors.

**Comment by draekien** [comment]
Thanks for raising this issue @jlipford, and thanks for using my library 😄 

I think I know what you are referring to, but just to confirm - you are talking about the `Limit` prop inside the `PaginatedRequest<T>` abstract class?

Can you please confirm that this is exactly what you are referring to (see PR #18)

**Comment by jlipford** [comment]
Yes, its the init modifier, I understand the intention but it imposes an unnecessary restriction IMO.   Sure thing! I was looking for someone who already implemented paging with Mediatr and this has filled that gap.

**Comment by jlipford** [comment]
Thank you for the update!

Just so you see the difference, the code to now generically apply paging to any Mediatr query with my 3rd party component library is FAR simplier.  (was having to use automapper and some mapping requirements).

        ///// <summary>
        ///// This will auto configure the paging properties from GridReadEventArgs grid type.
        ///// </summary>
        ///// <typeparam name="T">Register this query with AutoMapper to carry over any custom properties.</typeparam>
        ///// <typeparam name="TResult"></typeparam>
        ///// <param name="args"></param>
        ///// <param name="mapper"></param>
        ///// <param name="query"></param>
        ///// <returns></returns>
        ///// <remarks>You MUST register your query with AutoMapper. Only supports empty query constructors.</remarks>
        //public static T ToPaginatedQuery<T, TResult>(this GridReadEventArgs args, IMapper mapper, T query) 
        //    where T: PaginatedRequest<TResult>, new()
        //{
        //    //only supports empty constructor
        //    T pagingQuery = new T() 
        //    { 
        //        Limit = args.Request.PageSize,
        //        Offset = (args.Request.Page - 1) * args.Request.PageSize
        //    };

        //    //project the generic paging query into source, that way we maintain any custom source properties
        //    var mapped = mapper.Map<T, T>(query, pagingQuery);

        //    //if (mapper.ConfigurationProvider.CreateMapper) { throw new Exception("You must setup AutoMapper configuration for query type."); }

        //    return mapped;
        //}

        /// <summary>
        /// This will auto configure the paging properties from GridReadEventArgs grid type.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <typeparam name="TResult"></typeparam>
        /// <param name="args"></param>
        /// <param name="mapper"></param>
        /// <param name="query"></param>
        /// <returns></returns>
        public static T ToPaginatedQuery<T, TResult>(this GridReadEventArgs args, IMapper mapper, T query)
           where T : PaginatedRequest<TResult>, new()
        {
            query.Limit = args.Request.PageSize;
            query.Offset = (args.Request.Page - 1) * args.Request.PageSize;

            return query;
        }
